#ifndef MIBENGINESCONTROLLER_GLOBAL_H
#define MIBENGINESCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MIBENGINESCONTROLLER_LIBRARY)
#  define MIBENGINESCONTROLLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MIBENGINESCONTROLLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MIBENGINESCONTROLLER_GLOBAL_H
