#ifndef MIBPROTOTYPEVIDEOSTRATEGY_GLOBAL_H
#define MIBPROTOTYPEVIDEOSTRATEGY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MIBPROTOTYPEVIDEOSTRATEGY_LIBRARY)
#  define MIBPROTOTYPEVIDEOSTRATEGYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MIBPROTOTYPEVIDEOSTRATEGYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MIBPROTOTYPEVIDEOSTRATEGY_GLOBAL_H
