#ifndef MIBINFOSTRATEGY_GLOBAL_H
#define MIBINFOSTRATEGY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MIBINFOSTRATEGY_LIBRARY)
#  define MIBINFOSTRATEGYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MIBINFOSTRATEGYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MIBINFOSTRATEGY_GLOBAL_H
