#ifndef MIBSTATUSSTRATEGY_GLOBAL_H
#define MIBSTATUSSTRATEGY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MIBSTATUSSTRATEGY_LIBRARY)
#  define MIBSTATUSSTRATEGYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MIBSTATUSSTRATEGYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MIBSTATUSSTRATEGY_GLOBAL_H
