#ifndef MIBVIDEOSTREAMINGSTRATEGY_GLOBAL_H
#define MIBVIDEOSTREAMINGSTRATEGY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MIBVIDEOSTREAMINGSTRATEGY_LIBRARY)
#  define MIBVIDEOSTREAMINGSTRATEGYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MIBVIDEOSTREAMINGSTRATEGYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MIBVIDEOSTREAMINGSTRATEGY_GLOBAL_H
