#ifndef UNITTESTLIB_GLOBAL_H
#define UNITTESTLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UNITTESTLIB_LIBRARY)
#  define UNITTESTLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UNITTESTLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UNITTESTLIB_GLOBAL_H
