#ifndef MIBSETTINGSCLIENT_GLOBAL_H
#define MIBSETTINGSCLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MIBSETTINGSCLIENT_LIBRARY)
#  define MIBSETTINGSCLIENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MIBSETTINGSCLIENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MIBSETTINGSCLIENT_GLOBAL_H
