#ifndef MIBPICTURESTRATEGY_GLOBAL_H
#define MIBPICTURESTRATEGY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MIBPICTURESTRATEGY_LIBRARY)
#  define MIBPICTURESTRATEGYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MIBPICTURESTRATEGYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MIBPICTURESTRATEGY_GLOBAL_H
