#ifndef MIBGPIOINTERFACE_GLOBAL_H
#define MIBGPIOINTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MIBGPIOINTERFACE_LIBRARY)
#  define MIBGPIOINTERFACESHARED_EXPORT Q_DECL_EXPORT
#else
#  define MIBGPIOINTERFACESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MIBGPIOINTERFACE_GLOBAL_H
