#ifndef MIBAUTOPILOT_GLOBAL_H
#define MIBAUTOPILOT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MIBAUTOPILOT_LIBRARY)
#  define MIBAUTOPILOTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MIBAUTOPILOTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MIBAUTOPILOT_GLOBAL_H
